- name: "Playbook to copy local public key to remote authorized keys"
  hosts: "{{ hosts }}" 
  tasks:
    - name: "ping hosts"
      ping:
    - name: "Create the ~/.ssh folder"
      file:
        path: "~/.ssh"
        state: directory
        mode: "0755"
    - name: "Copy public keys to remote host authorized keys"
      copy:
        src: "{{ public_key }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
